apiVersion: v1
kind: Pod
metadata:
  name: cluster-entry
spec:
    containers:
    - image: ubuntu
      name: ubuntu
      # Just spin & wait forever
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      workingDir: "/imputation-results"
      resources:
        limits:
          cpu: "0.1"
          memory: "256Mi"
      volumeMounts:
      - mountPath: "/imputation-results"
        name: imputation-results
    volumes:
      - name: imputation-results
        persistentVolumeClaim:
          claimName: data-imputation-results
