apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-imputation-results
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: shared
